version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: net.dv8tion:JDA
    versions:
    - 4.2.0_227
    - 4.2.0_228
    - 4.2.0_229
    - 4.2.0_231
    - 4.2.0_235
    - 4.2.0_238
    - 4.2.0_240
    - 4.2.0_241
    - 4.2.0_242
    - 4.2.0_245
    - 4.2.0_246
  - dependency-name: com.sedmelluq:lavaplayer
    versions:
    - 1.3.66
    - 1.3.67
    - 1.3.69
    - 1.3.71
    - 1.3.72
  - dependency-name: com.github.johnrengelman.shadow
    versions:
    - 6.1.0
